apiVersion: apps/v1
kind: Deployment

metadata:
  name: clouddeploy

spec:
  replicas: 2

  selector:
    matchLabels:
      app: clouddeploy

  template:
    metadata:
      labels:
        app: clouddeploy

    spec:
      containers:
        - name: clouddeploy
          image: miteshbaikar307/clouddeploy:latest

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"

            limits:
              cpu: "250m"
              memory: "128Mi"
